### ISSUE TITLE
The given key was not present in the dictionary

### ISSUE THREAD

**Issue by josephderonde** [KilskyreMan/JiraToTfs#15]
Hi There,

Currently having an issue with the importer - i am using Jira Cloud and TFS15 (RC2) (which should import basically the same as 2015)

Stack trace is below - if you could shed any light that would be appreciated

only thing that is off is there is no one in the list to assign to (even though there are members in the team)

2016-11-11 12:31:30,702 [13] INFO TicketImporter.TicketImportAgent - Preparing to import
2016-11-11 12:31:31,077 [13] INFO TicketImporter.TicketImportAgent - Validating Jira tickets against TFS
2016-11-11 12:31:34,542 [13] ERROR JiraToTfs.Presenter.JiraToTfsPresenter - System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at TicketImporter.TfsPriorityMap.get_Item(String lookUp) in C:\Users\rondejo.INTERNAL\Desktop\JiraToTfs-1.0.1\TicketImporter\TfsPriorityMap.cs:line 58
   at TicketImporter.TfsProject.toWorkItem(Ticket toImport) in C:\Users\rondejo.INTERNAL\Desktop\JiraToTfs-1.0.1\TicketImporter\TfsProject.cs:line 306
   at TicketImporter.TfsProject.CheckTicket(Ticket toAdd, IFailedTicket& failure) in C:\Users\rondejo.INTERNAL\Desktop\JiraToTfs-1.0.1\TicketImporter\TfsProject.cs:line 424
   at TicketImporter.TicketImportAgent.StartImport() in C:\Users\rondejo.INTERNAL\Desktop\JiraToTfs-1.0.1\TicketImporter\TicketImportAgent.cs:line 119
   at JiraToTfs.Presenter.JiraToTfsPresenter.import_DoWork(Object sender, DoWorkEventArgs e) in C:\Users\rondejo.INTERNAL\Desktop\JiraToTfs-1.0.1\JiraToTfs\Presenter\JiraToTfsPresenter.cs:line 306

Cheers
Joe.

**Comment by josephderonde** [comment]
Ignore this i have managed to fix this with the information from #9

Cheers
Joe
